### ISSUE TITLE
Anyone interested?

### ISSUE THREAD

**Issue by wmorgenweck** [ActiveForums/ActiveForums#409] opened 2018-03-21 20:00 UTC
I have some extra time on my hands since leaving DNN Corp.  I'm wondering how many people still use this module.  Are people still deploying forums on their sites or have all conversations gone to Facebook? 

I was kicking the tires a bit this morning on Active Forums and would really like to dig back into the code.  Here are some of the things that really stood out to me:

- Overall UI seems dated.  
- Management is confusing.  There are some settings in Module settings and others in the control panel.  This should be streamlined a bit more.  
- Lots of extra code that really isn't necessary anymore.  We could clean this up and improve performance. 

Anyone else have any thoughts?

Thanks,
Will

**Comment by benjironelson** [comment] 2018-03-21 20:04
I think there is a need for forums on a website even in 2018. While a lot of conversations have gone to discord/slack/reddit/facebook it is still good to have a more-permanent, but also topic-specific place for communication.

**Comment by davidcoulter** [comment] 2018-03-21 21:14
Yes there is still interest. I just installed two separate forums to allow internal secure discussions for committees within a large corp.

Dave Coulter

eINNOVATIVE.ca
(905) 510-5809

**Comment by Plumifrons** [comment] 2018-03-21 21:29
Hi Will good to see you here.

I’m still using AF on many sites. The forums are not as busy as years ago but play still an important part on my sites. 

There are many parts of AF that can be improved but the main problem for me is the module settings. I have to change them in the sql tables. The module doesn’t save them and sometimes the forum stops working. It say that it can not find a template. Saving the settings without changing anything will fix it but it’s annoying for the users that the forum is down.

**Comment by wmorgenweck** [comment] 2018-03-21 22:11
> The module doesn’t save them and sometimes the forum stops working. It say that it can not find a template. Saving the settings without changing anything will fix it but it’s annoying for the users that the forum is down.

This would probably be one of the first things I would tackle.  I would move these settings back to the ActiveForums control panel.

**Comment by emo333** [comment] 2018-03-21 22:13
We use the the heck out of Active Forums on Intranet.  I agree could use a UI facelift for default install.  At minimum the existing open issues could be addressed/closed.

**Comment by johnhenley** [comment] 2018-03-21 22:19
I continue to use it as well for a public site with couple thousand active users. Better user preferences and forums subscription management would be high on my list.

John

On Mar 21, 2018, at 6:13 PM, Mitch <notifications@github.com<mailto:notifications@github.com>> wrote:


We use the the heck out of Active Forums on Intranet. I agree could use a UI facelift for default install. At minimum the existing open issues could be addressed/closed.

**Comment by mitchelsellers** [comment] 2018-03-22 02:15
@wmorgenweck If you have some time, i would LOVE some help!  There are a few bugs/issues that really need resolved among the other stuff

**Comment by artfuld** [comment] 2018-03-22 07:49
I have stopped using it unfortunately as everyone is moving to facebook. But if the development would become active I'd try and push everyone back to the forum.
My 2 cents though, is the base good enough to keep building on? Perhaps a sideproject would be to build it with some fancy new js-framework that we believe in.

**Comment by artfuld** [comment] 2018-04-02 20:05
I have been trying to go through old issues. But many issues are from 2015 or earlier with people stating their issue but not replying to comments. Probably because the answer was weeks after they posted the issue. I will try to close down issues that I understand as solved or that I can't reproduce with the latest version.

**Comment by mitchelsellers** [comment] 2018-04-02 20:28
That work would be appreciated.  I'm finally clearing some backlog here to be able to jump back in.  But if we can get a clean list of current issues that would be awesome

**Comment by artfuld** [comment] 2018-04-02 20:59
I have closed many old issues.
A summary of the remaining issues would probably be helpful, there are many duplicates. Some issues needs to be rechecked and all the feature enhancements would need some prioritizing.

**Comment by teambound** [comment] 2018-04-02 22:12
I think there is an opportunity with forums/social and while facebook provides a thread, there is no way to control it or organize it. I like the structure AF provides but believe it can be "rethought" around a social model that integrates with facebook in a unique way. I'm not big on facebook centric applications but leveraging social sharing has valuable benefits.

**Comment by artfuld** [comment] 2018-04-15 21:54
Hello everyone.
I have done some bug fixing, probably time to release it to the public especially due to the fixes for dnn9.2

I have closed a lot of issues, will try to sum up everything and post it here when I have the time.
The top 3 things people are saying is.
1. What's new module needs to work. Also some good suggestions to how to make it better.
2. Social groups. Ability to add more forums for a group and make sure that every link have the group id.
3. Design. As always there's the design problem. Lot's of talk about the templating engine needing to be fixed/updated but as stated in lots of threads this is a big job and it needs some thinking before someone goes in with a shovel.

**Comment by mitchelsellers** [comment] 2018-04-15 22:58
Can we chat tomorrow via Skype and get a release going?

Mitchel Sellers
Microsoft  MVP, ASPInsider, DNN MVP

Office: (515) 270-7063
Mobile: (515) 707-3629

Sent from my mobile device. Pardon any brevity or autocorrect mishaps

On Apr 15, 2018, at 16:54, Joakim Andersson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello everyone.
I have done some bug fixing, probably time to release it to the public especially due to the fixes for dnn9.2

I have closed a lot of issues, will try to sum up everything and post it here when I have the time.
The top 3 things people are saying is.

  1.  What's new module needs to work. Also some good suggestions to how to make it better.
  2.  Social groups. Ability to add more forums for a group and make sure that every link have the group id.
  3.  Design. As always there's the design problem. Lot's of talk about the templating engine needing to be fixed/updated but as stated in lots of threads this is a big job and it needs some thinking before someone goes in with a shovel.

**Closed** 2018-06-24 16:28 UTC
Labels: Discussion
