### ISSUE TITLE
FileUpload not working in Child Portal

### ISSUE THREAD

**Issue by vhert09** [ActiveForums/ActiveForums#317] opened 2015-08-31 03:47 UTC
DesktopModules/ActiveForums/API/ForumService/UploadFile returns 302.

I'm using AF 5.2.2 DNN 7.3.2.

If I use super user account the file succesfully uploaded. But using regular or site admin account file upload is not working.

I've tried to debug the code ForumServiceController.cs

var forumUser = new UserController().GetUser(ActiveModule.PortalID, ActiveModule.ModuleID, userInfo.UserID);

userInfo.UserID always -1

**Comment by vhert09** [comment] 2015-08-31 22:58
I just also find out. Attachment won't work on child portal.

**Comment by artfuld** [comment] 2015-09-11 08:43
There's allready a thread about this #289 
There seems to be a bug atm in DNN where API's simply can't get the UserInfo on Child portals.

There is probably a lot more that doesn't work in AF on child portals, such as the admin-page and everything else with a call to a service.

**Comment by efficiondave** [comment] 2017-01-19 20:50
I ran into this today too. The posted to URL doesn't include the subdirectory and so fails. Thinking there has to be a fairly simple standard solution to this type of issue for building the URL correctly...

**Comment by artfuld** [comment] 2018-04-15 21:40
Duplicate of #392

**Closed by artfuld** 2018-04-15 21:40 UTC
