### ISSUE TITLE
Problem with losing BB [img] tag on editing a post with text editor- 6.3.2 on DNN 8.5

### ISSUE THREAD

**Issue by lifesanadventure** [ActiveForums/ActiveForums#397] opened 2017-04-21 15:10 UTC
We can use the attachment section to embed an image in a post with the + button.  It adds the BB [img] tags.  But, if someone goes back to edit the post, we lose those tags and end up with HTML which doesn't function to embed the image.
Has anyone else encountered this or have a fix/workaround?
Thanx!
Glenn

**Comment by artfuld** [comment] 2018-04-15 21:46
Duplicate of #204

**Closed by artfuld** 2018-04-15 21:46 UTC
