### ISSUE TITLE
Package Version 06.03.00 has an assemblies error

### ISSUE THREAD

**Issue by RubyRengeek** [ActiveForums/ActiveForums#381] opened 2016-10-19 21:33 UTC
When using the DNN EVS to test the Installation ZIP file, I get the following error:

---

ExtensionMessageID: 1016342

ExtensionID: 92782

MessageTypeID: 1

MessageID: 93b81bb0-fded-447a-a720-f117f73d40e1

Message: The assemblies used in this extension, reference a higher version of DNN then the dependency “CoreVersion” in the manifest calls for.

Rule: PackageVerification.Rules.DependencyChecker

---

The line is <dependency type="CoreVersion">08.00.00</dependency>.

I have only downloaded the installable ZIP file, not the source code so there's been no additional compiling or NuGet updating of objects. Is there a solution to this?

**Comment by mitchelsellers** [comment] 2016-10-19 21:54
Which version of DNN are you installing to?


I'll fix the manifest for the next release.


________________________________

**Comment by RubyRengeek** [comment] 2016-10-19 22:00
I WILL BE installing to 08.04.00, but I never got to that point, unless I'm misunderstanding the process.  I'm using the EVS (http://evs.dnnsoftware.com).  I thought it was only verifying the package itself?  My understanding is once it passes this test I can install it on my system.

(As you can tell, I'm new to DNN).

**Comment by mitchelsellers** [comment] 2016-10-19 22:02
It depends on where you are installing, it will install and work, even with the EVS warning.  I can adjust the manifest in the next day or so, and most likely generate an updated build.  But you can still install to DNN without issue.


________________________________

**Comment by RubyRengeek** [comment] 2016-10-19 22:03
This is NOT a warning.  It was an ERROR.  Does that make a difference?

**Comment by mitchelsellers** [comment] 2016-10-19 22:18
No, the package still installs.  (The EVS system is for developers to know what is going on and it is wrong in the package, but you can still install.)


________________________________

**Comment by bogdan-litescu** [comment] 2016-12-22 12:49
Hey Mitchel,

Have you found a solution to this? We are getting this error now through EVS with one of the packages. The CoreDependency is 07.02.01 and I've just check all references with ILSpy and they point to DotNetNuke 7.2.1.367.

**Comment by mitchelsellers** [comment] 2016-12-26 15:26
Sadly, not a solid one as I'm seeing a similar issue.


EVS & DNN Versions seem to mismatch.  Need to try to look at this more


________________________________

**Comment by mitchelsellers** [comment] 2017-03-02 06:57
EVS issue was resolved in Version 6.3.2.  

Root cause was the "What's New" second module definition

**Closed by mitchelsellers** 2017-03-02 06:57 UTC
