### ISSUE TITLE
DNN 9.2.0

### ISSUE THREAD

**Issue by jncraig** [ActiveForums/ActiveForums#415] opened 2018-04-20 20:14 UTC
AF is broken with 9.2.0.

**Comment by artfuld** [comment] 2018-04-20 20:39
There's a pull request that fixes this. We just want a couple of more bugs ironed out and then we'll get the package sorted.

**Comment by jncraig** [comment] 2018-04-20 20:50
Thanks!  There was a comment over on the DNN Forums, which prompted me to
post the issue.  I assumed that it was known, but just wanted to make sure.

**Comment by vincentparrett** [comment] 2018-04-30 10:40
Any update on this, just about to migrate from dnn 7.4.2 to 9.2, but need to update this module first!

**Comment by artfuld** [comment] 2018-05-01 09:49
Could you test the version that's currently checked in here on github? It works fine on the environments I've tried but the save settings has created an error on one other site.

**Comment by Plumifrons** [comment] 2018-05-01 09:57
@artfuld, After updating that site to 9.2 the error was gone.

**Comment by artfuld** [comment] 2018-05-01 10:01
@Plumifrons that's awesome! and since it was just a errormessage and not a big error it should probably not be a problem to upgrade.
Strange, I tried it on my site from 7.4 -> 9.2 and could not reproduce the error. But glad it was "fixed".

I will try to wrap my head around some other minor bugs that can hopefully be fixed, and then we'll try to get a release

**Comment by vincentparrett** [comment] 2018-05-01 10:03
I have it running ok on 9,2 after building it locally. I will have to keep doing that though as I had to make changes to make my old 5.x theme work, because someone has hard coded a bunch of fontawesome stuff in everywhere grrrr.

**Comment by artfuld** [comment] 2018-05-04 21:42
Fixed in 06.03.03!

Will have a look at the html when I have the time

**Closed by artfuld** 2018-05-04 21:42 UTC
