### ISSUE TITLE
AF + CKEditor + Safari (mobile)

### ISSUE THREAD

**Issue by cmsfrotter** [ActiveForums/ActiveForums#259] opened 2015-04-23 16:14 UTC
Hi,
I want to use CKEditor (set as default DNN HTML Provider) on mobile devices inside AF, but somehow it's getting disabled on those. With my desktop browsers (Firefox & Chrome) it works just fine, but in mobile Safari there's just the standard textbox. At first I thought this'd be an issue with CKEditor or maybe something skin related, but when editing a HTML module within the mobile browser CKEditor is properly used and functional.
Is it hardcoded inside AF to not use HTML Provider on mobile / something like that or could this have another reason?

**Comment by supermansrf** [comment] 2015-04-23 16:46
This is by design apparently. It doesn't matter what html editor you use when viewing the forum from mobile it switches over to the simple editor. 


This whole thing needs rewritten eventually. I would like to see us move towards an integrated editor but this is way down the list of things to work on.

**Comment by cmsfrotter** [comment] 2015-04-28 14:42
Found it!

in controls\af_post.ascx.cs:
if (Request.Browser.IsMobileDevice)
            {
                _editorType = EditorTypes.TEXTBOX;
                _allowHTML = false;
            }

I just removed this and it works fine now. Thanks. An integrated editor would be great, but for the time being CKE does its job very well.

**Comment by artfuld** [comment] 2015-04-29 08:19
If I'm not mistaken there was a problem with ckeditor and especially android-phones. And that's the reason why it was disabled.

**Comment by cmsfrotter** [comment] 2015-04-29 08:42
I tried in out on android phone. Everything I tested out worked fine. Maybe this got fixed already with a CKE build?
At least on Safari and Chrome things seem to be ok. However, I can't speak for other mobile browsers.
Guess that if block can't be removed in general then, at least not without testing other browsers. But for me it's fine to do it :)

**Comment by artfuld** [comment] 2015-08-07 19:24
I have set this as an option in the next version. Closing this thread.

**Closed by artfuld** 2015-08-07 19:24 UTC
