### ISSUE TITLE
Can't approve a post

### ISSUE THREAD

**Issue by lfreer** [ActiveForums/ActiveForums#294] opened 2015-06-24 20:40 UTC
I turned on "Moderated" on a forum group. Now when a regular user submits a post, they get a notice that the post has to be approved, which is great.
But I can find no way to approve the post. I have signed in as a user with the right permissions set and as host and I see no place to go to approve pending posts. Where is it??

**Comment by supermansrf** [comment] 2015-06-26 01:02
So I worked with @lfreer and got her fixed on where to approve pending posts.  However there is still something else she is struggling with.  I don't use the moderation feature.  

Here is what her issue is.  When you have a forum set to moderated, a non-trusted user posts something.  It goes into the moderation queue.  The user gets an email stating that their post is waiting to be approved.  However as a post moderator, she isn't getting an email telling her that there is a post waiting to be moderated.  

If she manually looks there is a post in the queue that needs approved.  She approves it, and the user gets an email stating the post was approved.  

But the admin emails are still not getting sent.  Like I said I don't use this so I'm not sure what the expected behavior is or where to troubleshoot this.  

Does anyone use this feature that could possibly help out with a proper workflow and/or where to start looking?  I'm going to setup a test site with moderation enabled and going to try to look into this but I was hoping for someone who uses this feature more that knows what they are doing. 

Thanks

**Comment by johnhenley** [comment] 2015-06-26 11:20
She needs to look at her own user profile, at the communications tab.
Make sure it’s not set to ‘Never’ ☺
[cid:image002.jpg@01D0AFDE.6BDC3AE0]


John

**Comment by lfreer** [comment] 2015-06-29 21:58
Hi John,
No, my Moderator profile is set to "Instant" for email delivery.
And actually, the regular user account is not getting an email telling them that the post is waiting approval. But it does get an email when the post is approved or deleted.

**Comment by johnhenley** [comment] 2015-06-30 21:39
Also check in the AF control panel and look at the forum list.
For both the forum group and the forums under the group, look at the features tab.
Under moderation, you have to click on the elipsis and then select a template..

since there are separate options for approved, deleted, waiting/notification, etc. the ones that aren't working might be disabled...

**Comment by lfreer** [comment] 2015-06-30 22:00
Thanks for responding.
I did have a template selected. Here are the steps I have taken:
1.	I created a security role “Forum Admins”
2.	I created a user “LfreerUser” and added it to the ForumAdmins Role. 
3.	I went to the Forum Group in the Control Panel
        a.	Set Security to allow the “Forum Admins” role every single permission 
        b.	Went to the features tab and turned on “Moderated”
                 i.	Default Trust: Not Trusted
                ii.	Auto Trust Level: 0
                iii.	Notification: ModAlert
                iv.	Approved: PostApproved
                v.	Rejected: PostRejected
                vi.	Moved: PostMoved
               vii.	Deleted: PostDeleted
4.	Went to the test forum and made sure “Inherit Group Settings” was checked
5.	Logged in as a regular “Forum User” account and added a new topic in the test forum
        a.	Screen says “You have posted to a moderated forum…”
        b.	NO email is received in the email associated with the “LfreerUser” account
6.	Login as ‘LfreerUser” and click the “Moderate” link
7.	See the new topic and click “Approve”
        a.	New Topic now displays in the forum
        b.	Receive an email on the “Forum User” account: “Your topic has been approved…”

**Comment by johnhenley** [comment] 2015-07-02 17:29
I have a couple of things that are different.

1.       I’m using moderated forum without ‘inherit group settings’.

2.       Using ‘PostPending’ not ‘ModAlert’.

Under module settings, I have:
‘Enable Mail Queue – Yes’
‘ Messaging Type’ - Default Messaging’

John

**Comment by supermansrf** [comment] 2015-07-02 18:04
What @johnhenley states above for 1 and 2 will apply. 

Under module settings, messaging type should have nothing to do with this.  Messaging type is what private messaging you use.  You can select from default or if you use the ventrian module that is the other option.  

Mail queue has more to do with large batches of emails and I typically keep this turned off but have never messed with it.  It won't hurt to change this but it shouldn't make a difference.

**Comment by lfreer** [comment] 2015-07-02 19:09
I have tried these suggestions and it still does not work.
I know am trying in a moderated forum without "Inherit Group Settings".
I added the "Forum Admins" role to this individual forum and configured it to have every permission.
Moderated feature is on, and Notification is set to "Post Pending". 
I changed the mail queue and messaging type settings as suggested.

I still get no emails generated when a new message is posted. But the post does go into the moderator queue as before and emails are generated when it is approved or rejected.

**Comment by lfreer** [comment] 2015-07-06 22:13
Any other ideas on this? I still don't have this working and we are going to production tomorrow. I have gone round and round with my hosting company and they say it is not their issue. I am able to get other emails from the server.

**Comment by lfreer** [comment] 2015-07-08 23:11
I finally got in to debug it myself and found our particular issue. The Moderator notification does not send like the rest of the alert messages. It is sent through NotificationController.Instance.SendNotification, which is run through the scheduler. That led me to find a glitch in our schedule, which was not sending notifications due to a duplicate web server name. Quite a mess.
I would like it to use the nice customizable "Post Pending" template, but the code is hardcoded to use the Notification template in  controls/af_posts.cs line 966.
Barring that annoyance, everything is now doing what it should.

**Closed** 2015-08-11 19:08 UTC
